/* Auto-generated by cbindgen. Do not edit. */

#ifndef POLYGLOT_SQL_H
#define POLYGLOT_SQL_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define STATUS_SUCCESS 0

#define STATUS_PARSE_ERROR 1

#define STATUS_GENERATE_ERROR 2

#define STATUS_TRANSPILE_ERROR 3

#define STATUS_VALIDATION_ERROR 4

#define STATUS_INVALID_ARGUMENT 5

#define STATUS_SERIALIZATION_ERROR 6

#define STATUS_INTERNAL_ERROR 99

/**
 * Common result payload for string-returning FFI functions.
 */
typedef struct {
    /**
     * Result payload. Owned by caller and must be freed with `polyglot_free_string`.
     */
    char *data;
    /**
     * Error message payload. Owned by caller and must be freed with `polyglot_free_string`.
     */
    char *error;
    /**
     * Status code. `0` means success.
     */
    int32_t status;
} polyglot_result_t;

/**
 * Validation result payload for FFI.
 */
typedef struct {
    /**
     * `1` if valid, `0` otherwise.
     */
    int32_t valid;
    /**
     * JSON array of validation errors. Owned by caller and must be freed with `polyglot_free_string`.
     */
    char *errors_json;
    /**
     * Optional top-level error message.
     */
    char *error;
    /**
     * Status code. `0` means success.
     */
    int32_t status;
} polyglot_validation_result_t;

/**
 * Parse SQL and annotate the AST with inferred type information.
 *
 * Returns a JSON array of Expression objects with `inferred_type` fields
 * populated on value-producing nodes.
 *
 * If `schema_json` is NULL or empty, type annotation runs without schema
 * (only literal and operator types are inferred). With a schema, column
 * types are resolved from the provided table definitions.
 */
polyglot_result_t polyglot_annotate_types(const char *sql,
                                          const char *dialect,
                                          const char *schema_json);

/**
 * Qualify table references in AST JSON.
 *
 * `ast_json` must encode `Vec<Expression>`, matching `polyglot_parse` output.
 */
polyglot_result_t polyglot_qualify_tables(const char *ast_json, const char *options_json);

/**
 * Set LIMIT on AST JSON.
 *
 * `ast_json` must encode `Vec<Expression>`, matching `polyglot_parse` output.
 */
polyglot_result_t polyglot_set_limit(const char *ast_json, uint64_t limit);

/**
 * Set OFFSET on AST JSON.
 *
 * `ast_json` must encode `Vec<Expression>`, matching `polyglot_parse` output.
 */
polyglot_result_t polyglot_set_offset(const char *ast_json, uint64_t offset);

/**
 * Set ORDER BY on AST JSON.
 *
 * `ast_json` and `order_by_json` must encode `Vec<Expression>`.
 */
polyglot_result_t polyglot_set_order_by(const char *ast_json, const char *order_by_json);

/**
 * Rename tables in AST JSON with options.
 *
 * `ast_json` must encode `Vec<Expression>`, matching `polyglot_parse` output.
 */
polyglot_result_t polyglot_rename_tables_with_options(const char *ast_json,
                                                      const char *mapping_json,
                                                      const char *options_json);

/**
 * Return supported dialect names as JSON.
 */
char *polyglot_dialect_list(void);

/**
 * Return number of supported built-in dialects.
 */
int32_t polyglot_dialect_count(void);

/**
 * Return the library version.
 *
 * Returned pointer is statically allocated and must not be freed.
 */
const char *polyglot_version(void);

/**
 * Compute AST diff between two SQL statements.
 */
polyglot_result_t polyglot_diff(const char *sql1, const char *sql2, const char *dialect);

/**
 * Pretty-print SQL for a dialect.
 */
polyglot_result_t polyglot_format(const char *sql, const char *dialect);

/**
 * Pretty-print SQL for a dialect with explicit formatting guard options.
 *
 * `options_json` must be a JSON object compatible with `FormatGuardOptions`, e.g.
 * `{"maxInputBytes": 16777216, "maxTokens": 1000000, "maxAstNodes": 1000000, "maxSetOpChain": 256}`.
 */
polyglot_result_t polyglot_format_with_options(const char *sql,
                                               const char *dialect,
                                               const char *options_json);

/**
 * Generate SQL from AST JSON.
 *
 * `ast_json` must encode `Vec<Expression>`.
 */
polyglot_result_t polyglot_generate(const char *ast_json, const char *dialect);

/**
 * Generate SQL from a standalone DataType JSON object.
 */
polyglot_result_t polyglot_generate_data_type(const char *data_type_json, const char *dialect);

/**
 * Trace column lineage in a SQL statement.
 */
polyglot_result_t polyglot_lineage(const char *column_name, const char *sql, const char *dialect);

/**
 * Trace column lineage in a SQL statement using schema metadata.
 */
polyglot_result_t polyglot_lineage_with_schema(const char *column_name,
                                               const char *sql,
                                               const char *schema_json,
                                               const char *dialect);

/**
 * Get source tables that contribute to a column.
 */
polyglot_result_t polyglot_source_tables(const char *column_name,
                                         const char *sql,
                                         const char *dialect);

/**
 * Free a C string returned by this library.
 */
void polyglot_free_string(char *s);

/**
 * Free a `polyglot_result_t`.
 */
void polyglot_free_result(polyglot_result_t result);

/**
 * Free a `polyglot_validation_result_t`.
 */
void polyglot_free_validation_result(polyglot_validation_result_t result);

/**
 * Build an OpenLineage columnLineage facet and dataset payload.
 *
 * `options_json` must be a JSON object compatible with `OpenLineageOptions`.
 */
polyglot_result_t polyglot_openlineage_column_lineage(const char *sql, const char *options_json);

/**
 * Build an OpenLineage JobEvent payload. This does not send the event.
 *
 * `options_json` must be a JSON object compatible with `OpenLineageOptions`.
 */
polyglot_result_t polyglot_openlineage_job_event(const char *sql, const char *options_json);

/**
 * Build an OpenLineage RunEvent payload. This does not send the event.
 *
 * `options_json` must be a JSON object compatible with `OpenLineageOptions`.
 */
polyglot_result_t polyglot_openlineage_run_event(const char *sql, const char *options_json);

/**
 * Parse, optimize (full pipeline), and generate SQL.
 */
polyglot_result_t polyglot_optimize(const char *sql, const char *dialect);

/**
 * Parse SQL into an AST JSON string.
 */
polyglot_result_t polyglot_parse(const char *sql, const char *dialect);

/**
 * Parse a single SQL statement into a JSON AST object.
 */
polyglot_result_t polyglot_parse_one(const char *sql, const char *dialect);

/**
 * Parse a standalone SQL data type into a JSON DataType object.
 */
polyglot_result_t polyglot_parse_data_type(const char *sql, const char *dialect);

/**
 * Return compact query analysis facts for a SELECT or set operation.
 *
 * `options_json` must be a JSON object compatible with `AnalyzeQueryOptions`.
 */
polyglot_result_t polyglot_analyze_query(const char *sql, const char *options_json);

/**
 * Tokenize SQL into a JSON array of tokens.
 */
polyglot_result_t polyglot_tokenize(const char *sql, const char *dialect);

/**
 * Transpile SQL between dialects using dialect names.
 */
polyglot_result_t polyglot_transpile(const char *sql,
                                     const char *from_dialect,
                                     const char *to_dialect);

/**
 * Transpile SQL between dialects with explicit transpile options.
 *
 * `options_json` must be a JSON object compatible with `TranspileOptions`, e.g.
 * `{"pretty": true, "unsupportedLevel": "raise"}`. Unknown fields are ignored;
 * omitted fields use their defaults.
 */
polyglot_result_t polyglot_transpile_with_options(const char *sql,
                                                  const char *from_dialect,
                                                  const char *to_dialect,
                                                  const char *options_json);

/**
 * Validate SQL syntax for a dialect.
 */
polyglot_validation_result_t polyglot_validate(const char *sql, const char *dialect);

#endif  /* POLYGLOT_SQL_H */
